### ISSUE TITLE
Grafana Dashboard is Blank. 

### ISSUE THREAD

**Issue by gravyflex** [opc40772/pfsense-graylog#12]
My grafana dashboard is blank. I think I got all the steps in the document. 

Does anyone have any clues on what I could be missing? 
![image](https://user-images.githubusercontent.com/7466316/52190041-38d46500-2802-11e9-8814-c50acc4f18a0.png)

![image](https://user-images.githubusercontent.com/7466316/52189979-ad5ad400-2801-11e9-9b5f-937b7e3f85e7.png)

pfsense version
![image](https://user-images.githubusercontent.com/7466316/52189986-bb105980-2801-11e9-96c0-d44116de3f8a.png)

Elastic search version
```
apt-cache policy elasticsearch
elasticsearch:   Installed: 5.6.14
```

Graylog server
```
apt-cache policy graylog-server
graylog-server:  Installed: 2.4.6-1
```

Grafana
`grafana:   Installed: 5.4.2`

**Comment by apedroamarques** [comment]
Hi,

I add the same issue for the dashboard, I simply ignore it and build my own, but please check if you have all the plugins installed, including the Heatmap by Jeremy Branham. For what I was able to dig around, I think the issue can be because of the use of a field in the Grafana dashboard that is not present in the Elastic Search DB, the field is: timestamp_graf and is used by several panels on the dashboard, try to edit the dashboard and replace all occurrences of it to real_timestamp.
Maybe it can work..

Regards

**Comment by gravyflex** [comment]
I was missing one of the plugins as you thought. Also adjusting timestamp_graf did not work.
